### ISSUE TITLE
Lesezeichenmarker auf Startseite

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#202]
- Besuchte Themenfelder bekommen auf Startseite ein Lesezeichenmarker (aus Lesepfad ermittelt)
- Klick auf eine solche Markierung öffnet kleines Fensterchen, mit dem man das Lesezeichen löschen kann
- Klick auf Themenfeld führt zum zuletzt gelesenen Textknoten des Themenfeldes

**Comment by michaelgiesler** [comment]
In der Demo muss dieses Feature aufgrund eines Cookies implementiert werden.

**Comment by michaelgiesler** [comment]
- [ ] #313 - Themenfeldbilder auf der Startseite mit einem optionalen Lesezeichen-Icon versehen
- [ ] #314 - Bei jedem Textknotenaufruf diesen als Lesezeichen für das jeweilige Themenfeld speichern
- [ ] #315 - Im Dashboard-Controller die Lesezeichen aus User-Objekt an das Template weiterreichen
