### ISSUE TITLE
Standard-Finanzierungsseite

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#230]
Der Leser soll merken, wieso die Geschichte an dem jeweiligen Textknoten endet, und er soll erfahren, was er tun soll, damit die Geschichte weitergeht. Der Leser soll zu Patreon geleitet werden, wo er textknotenunabhängig für eine Fortsetzung spenden kann.
- [x] Seite designen: #249
- [x] Text für diese Seite schreiben: #250
- [x] Finanzierungsknoten müssen als Finanzierungsseite dargestellt werden. (haben keine Folgeknoten): #251
- [x] Bezahlschranke muss für Finanzierungsknoten abgestellt werden: #252

**Comment by michaelgiesler** [comment]
Können wir die bereits zusammengekommene Summe auf wzl anzeigen? API?
Wir funktioniert die Finanzierung von Projekten auf Patreon?
